[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

# Configuración del tema visual
[theme]
primaryColor = "#FF6B6B"               
backgroundColor = "#F7F7F7"            
secondaryBackgroundColor = "#FFFFFF"   
textColor = "#333333"                 
font = "sans serif"         
